### DISCUSSION TITLE
세벌식 390 사용 중인데, 한글 사용 중 숫자패드를 누르면 숫자 대신 한글 글자가 입력됩니다.

### DISCUSSION THREAD

**Discussion by kimhongsu** [Riey/kime#577] [Q&A] [answered]
세벌식 390 사용 중인데, 한글 사용 중 숫자패드를 누르면 숫자 대신 한글 글자가 입력됩니다.
영어(Qwerty)로 사용 중일 때 카보드 오른 쪽 숫자패드를 누르면 숫자가 입력됩니다.
한글일 때 숫자패드가 숫자로 작동하게 하는 설정이 따로 있을까요?

~/.config/kime/config.yaml
설정 파일의 내용은 다음과 같습니다.

```
---
daemon:
  modules:
    - Xim
    - Wayland
    - Indicator
indicator:
  icon_color: Black
log:
  global_level: DEBUG
engine:
  default_category: Latin
  global_category_state: false
  global_hotkeys:
    M-C-Backslash:
      behavior:
        Mode: Math
      result: ConsumeIfProcessed
    S-Space:
      behavior:
        Toggle:
          - Hangul
          - Latin
      result: Consume
    Super-Space:
      behavior:
        Toggle:
          - Hangul
          - Latin
      result: Consume
    M-C-E:
      behavior:
        Mode: Emoji
      result: ConsumeIfProcessed
    Esc:
      behavior:
        Switch: Latin
      result: Bypass
    Muhenkan:
      behavior:
        Toggle:
          - Hangul
          - Latin
      result: Consume
    AltR:
      behavior:
        Toggle:
          - Hangul
          - Latin
      result: Consume
    Hangul:
      behavior:
        Toggle:
          - Hangul
          - Latin
      result: Consume
    C-Space:
      behavior:
        Toggle:
          - Hangul
          - Latin
      result: Consume
  category_hotkeys:
    Hangul:
      ControlR:
        behavior:
          Mode: Hanja
        result: Consume
      HangulHanja:
        behavior:
          Mode: Hanja
        result: Consume
      F9:
        behavior:
          Mode: Hanja
        result: ConsumeIfProcessed
  mode_hotkeys:
    Math:
      Enter:
        behavior: Commit
        result: ConsumeIfProcessed
      Tab:
        behavior: Commit
        result: ConsumeIfProcessed
    Hanja:
      Enter:
        behavior: Commit
        result: ConsumeIfProcessed
      Tab:
        behavior: Commit
        result: ConsumeIfProcessed
    Emoji:
      Enter:
        behavior: Commit
        result: ConsumeIfProcessed
      Tab:
        behavior: Commit
        result: ConsumeIfProcessed
  xim_preedit_font:
    - D2Coding
    - 15.0
  latin:
    layout: Qwerty
    preferred_direct: true
  hangul:
    layout: sebeolsik-3-90
    word_commit: false
    addons:
      all:
        - ComposeChoseongSsang
        - FlexibleComposeOrder
      dubeolsik:
        - TreatJongseongAsChoseong
```
