### ISSUE TITLE
Validate config with proper error messages

### ISSUE THREAD

**Issue by xnuk** [Riey/kime#264]
```yaml
# For example, this config file does not work and it makes no error messages,
# while Kime ignores entire config in this file.

hotkeys:
  Z:
    behavior: ToggleHangul
    result: Bypass
  AltR:
    behavior: ToggleHangul
    result: Consume
  AltL:
    behavior: ToggleHangul
    result: Consume

# Because `AltL` is not defined currently (v1.0.3).
```
