### ISSUE TITLE
Alt나 Ctrl을 조합한 단축키 사용하려 하면 커서가 움직여버려서 한자입력을 못 합니다.

### ISSUE THREAD

**Issue by wind0204** [Riey/kime#522]
kime version : kime 2.5.5
wayland compositor : sway 1.6-92ba2290 (Jun  1 2021, branch 'master')

제 키보드에 한자버튼이 없어서 M-Space와 C-F9를 사용하여 한자를 입력하려 했습니다.
```
  category_hotkeys:
    Hangul:
      M-Space:
        behavior:
          Mode: Hanja
        result: Consume
      HangulHanja:
        behavior:
          Mode: Hanja
        result: Consume
      C-F9:
        behavior:
          Mode: Hanja
        result: ConsumeIfProcessed
```

그런데 Alt나 Ctrl을 누를때마다 커서가 움직여서 그런지 한자입력이 안 됩니다.
C-F9 를 F9로 변경해서 실험해보니 한자입력이 가능하네요.

감사합니다!

**Comment by Riey** [comment]
```yaml
ContorlL:
    behavior: Ignore
    result: Bypass
```

이렇게 추가해보세요

**Comment by wind0204** [comment]
그렇게 추가하니 고쳐졌습니다! 이제 share/doc/kime/default_config.yaml 에 아래 여섯줄만 추가되면 마무리될 것같네요.. :
```
    ControlL:
      behavior: Ignore
      result: Bypass
    AltL:
      behavior: Ignore
      result: Bypass
```
