### ISSUE TITLE
`kime-xim` 실행 시 패닉

### ISSUE THREAD

**Issue by zmtq05** [Riey/kime#554]
`kime-xim` 실행시 패닉이 발생합니다.

AUR `kime-git` 사용중입니다.

```
$ kime-xim
[ INFO] Found previous XIM_SERVER it will overrided
[ INFO] Start server win: 60817408
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/frontends/xim/src/handler.rs:50:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

```
$ kime-check
KIME_API_VERSION: 6
Ok       Engine api version
Found icon: /usr/share/icons/hicolor/64x64/apps/kime-hangul-black.png
Found icon: /usr/share/icons/hicolor/64x64/apps/kime-hangul-white.png
Found icon: /usr/share/icons/hicolor/64x64/apps/kime-latin-black.png
Found icon: /usr/share/icons/hicolor/64x64/apps/kime-latin-white.png
Ok       Check icons exists
Loading config path: /home/sloth/.config/kime/config.yaml
Ok       Config file
Ok       Engine works
Ok       XMODIFIERS has @im=kime
Ok       GTK_IM_MODULE has kime
Ok       QT_IM_MODULE has kime
Ok       LANG has UTF-8
```

```yml
# ~/.config/kime/config.yaml
---
daemon:
  modules:
    - Xim
log:
  global_level: DEBUG
engine:
  hangul:
    addons:
      dubeolsik:
        - TreatJongseongAsChoseong
```
