### ISSUE TITLE
dvorak 작동 안함

### ISSUE THREAD

**Issue by sepiabrown** [Riey/kime#626]
````
daemon:
  modules:
  - Xim
  - Wayland
  - Indicator
indicator:
  icon_color: Black
log:
  global_level: DEBUG
engine:
  translation_layer: null
  default_category: Latin
  global_category_state: false
  global_hotkeys:
    M-C-Backslash:
      behavior: !Mode Math
      result: ConsumeIfProcessed
    Super-Space:
      behavior: !Toggle
      - Hangul
      - Latin
      result: Consume
    M-C-E:
      behavior: !Mode Emoji
      result: ConsumeIfProcessed
    Esc:
      behavior: !Switch Latin
      result: Bypass
    Muhenkan:
      behavior: !Toggle
      - Hangul
      - Latin
      result: Consume
    AltR:
      behavior: !Toggle
      - Hangul
      - Latin
      result: Consume
    Hangul:
      behavior: !Toggle
      - Hangul
      - Latin
      result: Consume
  category_hotkeys:
    Hangul:
      ControlR:
        behavior: !Mode Hanja
        result: Consume
      HangulHanja:
        behavior: !Mode Hanja
        result: Consume
      F9:
        behavior: !Mode Hanja
        result: ConsumeIfProcessed
  mode_hotkeys:
    Math:
      Enter:
        behavior: Commit
        result: ConsumeIfProcessed
      Tab:
        behavior: Commit
        result: ConsumeIfProcessed
    Hanja:
      Enter:
        behavior: Commit
        result: ConsumeIfProcessed
      Tab:
        behavior: Commit
        result: ConsumeIfProcessed
    Emoji:
      Enter:
        behavior: Commit
        result: ConsumeIfProcessed
      Tab:
        behavior: Commit
        result: ConsumeIfProcessed
  candidate_font: Noto Sans CJK KR
  xim_preedit_font:
  - Noto Sans CJK KR
  - 15.0
  latin:
    layout: Dvorak
    preferred_direct: true
  hangul:
    layout: dubeolsik
    word_commit: false
    preedit_johab: Needed
    addons:
      all:
      - ComposeChoseongSsang
      dubeolsik:
      - TreatJongseongAsChoseong
```

**Comment by nemonein** [comment]
안녕하세요. 영문 Dvorak 자판 사용자입니다.
예전부터 Dvorak 을 어떻게 쓰는게 맞는 방법인지 고민을 해왔는데..
저는 OS(KDE) 에서 Dvorak 자판을 선택하고, 설정은 그냥 QWERTY 로 해서 사용하고 있습니다.
물론 아무 이상은 없습니다.

```
  latin:
    layout: Qwerty
    preferred_direct: true
  hangul:
    layout: dubeolsik
    word_commit: false
    preedit_johab: Needed
    addons:
      all:
      - ComposeChoseongSsang
      dubeolsik:
      - TreatJongseongAsChoseong

```
단지 Dvorak 자판을 사용하지 못하셔서 글을 올리셨는지, 아니면 다른 사항 때문에 올리셨는지는 모르겠지만, 아무튼 영문 Dvorak 자판을 쓸 수는 있다는 사실을 말씀드리려고 덧글 올려봤습니다.
