### ISSUE TITLE
Need keymap for right super

### ISSUE THREAD

**Issue by ToroidalFox** [Riey/kime#640]
Apple's keyboard has right-command which is right-super in linux, in traditional right-alt location. Lack of right super mapping means I can't use this key as category toggle key.

**Comment by Riey** [comment]
[#752](https://github.com/Riey/kime/pull/752)에서 `SuperL`/`SuperR` 키코드를 추가했습니다. 이제 설정 파일에서 아래처럼 오른쪽 Super(맥 키보드의 오른쪽 Command) 키를 한/영 전환에 쓰실 수 있습니다.

```yaml
engine:
  global_hotkeys:
    SuperR:
      behavior: !Toggle [Hangul, Latin]
      result: Consume
```

이 기능은 3.2.0에 포함되어 릴리스되었습니다. 참고로 Wayland 네이티브 앱에서 수식키 단독 단축키가 동작하지 않던 문제는 [#760](https://github.com/Riey/kime/pull/760)에서 별도로 수정되어 다음 릴리스에 포함될 예정입니다. 제안 감사합니다!
