### ISSUE TITLE
세벌식에서는 ComposeJungseongSsang 기능이 작동을 안하나요?

### ISSUE THREAD

**Issue by forteleaf** [Riey/kime#679]
세벌식을 사용하고 있습니다.
ComposeJungseongSsang 기능을 사용하려고 하는데, 안 됩니다.
원래 이런 것인가요?

```
ㅑ + ㅣ = ㅒ
ㅕ + ㅣ = ㅖ
```

**Comment by Riey** [comment]
That feature is not enabled by default. Please turn it on by addon configuration. (see docs/CONFIGURATION.ko.md)

**Comment by forteleaf** [comment]
> That feature is not enabled by default. Please turn it on by addon configuration. (see docs/CONFIGURATION.ko.md)

이렇게 설정을 했습니다.
```yaml
...
  xim_preedit_font:
  - D2Coding
  - 15.0
  latin:
    layout: Qwerty
    preferred_direct: true
  hangul:
    layout: sebeolsik-3-90
    word_commit: false
    preedit_johab: Needed
    addons:
      all:
      - ComposeChoseongSsang      # 값은 자음을 두번 누르면 쌍자음으로 전환
      - ComposeJungseongSsang     # ㅏ + ㅣ = ㅐ 가 되는 기능인데 세벌식에서 안되는 듯?
      dubeolsik:
      - TreatJongseongAsChoseong  # 종성을 초성 취급한다.
```
