### ISSUE TITLE
Intellij, Gitnuro등 자바로 만들어진 앱에서 한글입력이 안됩니다.

### ISSUE THREAD

**Issue by strictpvp** [Riey/kime#703]
OS: EndeavourOS
Kernel: Linux 6.14.7-zen2-1-zen
DE: KDE Plasma 6.3.5 (wayland)

자바를 제외한 다른 앱들은 전부 잘 작동합니다.
x11 환경에서도 동일한 증상이 있습니다.

런타임 의존성 전부 설치되어 있고 readme에 있는 방법은 다 해봤습니다.
설치는 yay -Syy kime-git 으로 설치했습니다.

영상: https://streamable.com/65y9pz

**Comment by xvzc** [comment]
`kime-xim` 이 잘 떠있나요? 
config file도 공유해주시면 좋을 것 같아요.

**Comment by xvzc** [comment]
아 .. 영상에 올려주셨었군요. 혹시 D2Coding 폰트가 설치되어있으신가요? 
저도 최근에 Wayland + Hyprland 환경으로 넘어왔는데 Intellij는 아니였지만 특정 앱에서 한글이 입력되지 않는 이슈를 겪었었어요.
D2Coding 폰트를 설치하고나서 해결된 경험이있습니다.

방금 저도 IntelliJ를 설치해서 테스트 해봤는데 잘 되는 것 같아요.

**Comment by strictpvp** [comment]
기본 config 파일 사용중입니다.
config 파일에 명시되어있는 폰트를 설치 했음에도 입력이 여전히 안됩니다. (D2Coding으로도 바꿔서 해봤습니다)
혹시 @xvzc 님이 사용중인 config 파일을 공유 해주실 수 있으신가요?

**Comment by xvzc** [comment]
```yaml
daemon:
  modules: [Xim,Wayland,Indicator]
indicator:
  icon_color: White
log:
  global_level: DEBUG
engine:
  translation_layer: null
  default_category: Latin
  global_category_state: false
  global_hotkeys:
    Super-Space:
      behavior: !Toggle
        - Hangul
        - Latin
      result: Consume
    Esc:
      behavior: !Switch Latin
      result: Bypass
```

```
❯ kime-check
KIME_API_VERSION: 7
Ok       Engine api version                      
Found icon: /run/current-system/sw/share/icons/hicolor/64x64/apps/kime-hangul-black.png
Found icon: /run/current-system/sw/share/icons/hicolor/64x64/apps/kime-hangul-white.png
Found icon: /run/current-system/sw/share/icons/hicolor/64x64/apps/kime-latin-black.png
Found icon: /run/current-system/sw/share/icons/hicolor/64x64/apps/kime-latin-white.png
Ok       Check icons exists                      
Loading config path: /etc/xdg/kime/config.yaml
Ok       Config file                             
Ok       Engine works                            
Ignore   XMODIFIERS has @im=kime                 (Session type is wayland not x11)
Ok       GTK_IM_MODULE has kime                  
Ok       QT_IM_MODULE has kime                   
Ok       LANG has UTF-8                          
Ignore   Plasma virtual keyboard has kime        (Current desktop and session type is Hyprland and wayland, not KDE and wayland)
```
저는 이렇게 되어있습니다.
